import Header from '@/components/Header/Header'
// import { getServerSession } from 'next-auth'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MarketLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
