import { getServerSession } from 'next-auth';
import '../globals.css'
import { authOptions } from '@/pages/api/auth/[...nextauth]';

export const metadata = {
    title: 'Create Next',
    description: 'Generated by create next app',
}


export default async function PlaygroundLayout({ children }) {
    const session = await getServerSession(authOptions);
    console.log("get session : ", session)

    console.log("Layout Trigger")
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
