import { getServerSession } from 'next-auth';
import '../globals.css'
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getToken } from 'next-auth/jwt';

export const metadata = {
    title: 'Create Next',
    description: 'Generated by create next app',
}

async function getTok() {
    const tok = await fetch("http://localhost:3000/api/user/restricted");
    return tok.json()
}


export default async function PlaygroundLayout({ children }) {
    const session = await getServerSession(authOptions);
    console.log("get session : ", session)

    console.log("Layout Trigger")
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
